import type { Metadata } from "next";
import "./globals.css";
import { DetailsProvider } from "@/components/DetailsContext";


export const metadata: Metadata = {
  title: "AI Resume Builder",
  description: "Generated by create next app",
};

export default function RootLayout({
  children,
}: Readonly<{
  children: React.ReactNode;
}>) {
  return (
    <html lang="en">
      <body>
        <DetailsProvider>
          {children}
        </DetailsProvider>
      </body>
    </html>
  );
}
