# Generated by Django 5.1.1 on 2024-09-26 23:01

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('ai', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='projects',
            name='project_description',
            field=models.TextField(default='nothing'),
            preserve_default=False,
        ),
    ]
